[tools]
bitwarden-secrets-manager = "latest"
usage = "latest"

[env]
LOCAL_SCOPE = "Peacock"
_.source = "{{config_root}}/.scripts/load_env.sh"

[task_config]
includes = ["./tasks"]

[hooks]
cd = "mise run ghauth"

[settings]
experimental = true
